services:
  api:
    build:
      context: ./api
    restart: always
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    environment:
      - PORT=${PORT:-3001}
      - DATABASE_URL=file:./prisma/dev.db

  app:
    build:
      context: ./app
    ports:
      - "3000:3000"
    depends_on:
      - api
